openapi: 3.0.0
info:
  title: Vipul Portfolio API
  description: The swagger documentation for portfolio
  version: 0.0.1
servers:
  - url: http://localhost:1000/
    description: Local host server
paths:
  /login:
    post:
      summary: Creates a user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Created
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      message:
                        type: string
                      status:
                        type: integer
                  - type: object
                    properties:
                      success:
                        type: string
                      accessToken:
                        type: string
                      refreshToken:
                        type: string
